---
title: "hw2"
author: "Tamara Zdorova"
output: html_notebook
---

```{r}
### 1.1
library(tibble)
library(dplyr)
df1 = readr::read_csv('https://raw.githubusercontent.com/agricolamz/2018_data_analysis_for_linguists/master/data/students/tozdo/hw2_agreement/hw2_1_zilo_class.csv')
df1 %>%
  distinct(stimulus_source, translation_ru) %>%
  count(stimulus_source)
head(df1)
```
```{r}
### 1.2
library(tidyr)
library(irr)
df1 %>% 
  select(s_id, stimulus, translation_ru, stimulus_source, class) %>% 
  spread(key = s_id, value = class) ->
  df1_short
agree(df1_short[,-c(1:3)])
```
```{r}
### 1.3
zilo_classes_2s <- df1_short[,c(7, 11)]
kappa2(zilo_classes_2s)
```
```{r}
### 1.4
kappam.fleiss(df1_short[,-c(1:3)])
```
```{r}
### 1.5
Мы исследовали наличие вариативности в распределении исконных и заимствованных слов в зиловском диалекте андийского языка. Процент полного согласия между информантами составил 73%, каппа Коэна получилась равной 0.77, а каппа Фляйса -- 0.85. Такие результаты свидетельствуют о высокой согласованности между говорящими.
```
```{r}
### 2.1
df2 = readr::read_csv('https://raw.githubusercontent.com/agricolamz/2018_data_analysis_for_linguists/master/data/students/tozdo/hw2_agreement/hw2_2_verbs.csv')
df2 %>% 
  distinct(SubjectCode) %>% 
  count()
```
```{r}
### 2.2
df2 %>%
  group_by(WordType, Gender) %>% 
  summarize(mean = mean(GivenScore))
```
```{r}
### 2.3
df2 %>% 
  select(SubjectCode, Stimulus, GivenScore) %>% 
  drop_na() %>%
  spread(key = Stimulus, value = GivenScore) ->
  df2_short
agree(df2_short[,-c(1)])

```
```{r}
### 2.4
kappam.fleiss(df2_short[,-c(1)])
```
```{r}
### 2.5
icc(df2_short[,-c(1)], model = "twoway", type = "agreement")
```
```{r}

```
